[package]
name = "shit"
version = "0.1.0"
authors = ["Chintal Dholakiya <chintal3198@gmail.com>"]
description = "Shit: An cli app resonating git client"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
sha1 = "0.10.6"
flate2 = "1.0"
byteorder = "1.4"
hex = "0.4"
